# Generated by Django 4.2.9 on 2024-01-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraperapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='strinname',
            new_name='string_name',
        ),
    ]
